import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"
import Header from "@/components/header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${poppins.className} max-w-[1444px] mx-auto px-4 sm:px-6 lg:px-8 py-8
          bg-neutral-700 `}
      >
        <div className="absolute inset-0 bg-fuchsia-800 bg-[size:20px_20px] -z-10 opacity-20 blur-[100px]"></div>
        <Header />
        {children}
      </body>
    </html>
  );
}
